spring:
  application:
    name: phone-records

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT:8080}

abstractapi:
  phone-validation:
    api:
      key: ${ABSTRACT_API_KEY}
      url: ${ABSTRACT_API_URL}
